### PR TITLE
Fix core, service and service-api issues

### LINKED ISSUE #7532: [GreenCityUser, Sonar] Fix Issues in GreenCityUser service and service-api modules
Improve Maintainability in GreenCityUser Service and Service-API Modules

### Changes Required:

- ApiLocate.java: Remove the @parameters section for clarity and conciseness.
- CustomExceptionHandlerTest.java: Eliminate unnecessary commented-out test cases and correct the value assignments for improved test clarity.
- ManagementSecurityControllerTest.java: Remove redundant local variable assignments for dto.
- JwtTool.java: Replace RuntimeException with a more specific IllegalArgumentException to enhance exception handling and add requirement handler exception.
- Annotations: Add @SuppressWarnings("java:S1118") to EmailAddressValidator, LanguageValidationUtils, and UrlValidator to bypass SonarLint issues.
- Mocking Updates: Replace the deprecated initMocks with @ExtendWith(MockitoExtension.class) in SearchCriteriaTest.java, CustomSpecificationTest.java, and UserSpecificationTest.java.
- Code Refactor (OwnSecurityServiceImplTest.java): Rename the field notVerifiedUser and refactor lambdas to ensure only one exception-throwing invocation per lambda.
- VerifyEmailServiceImplTest.java: Remove commented-out code blocks that are no longer needed.
- UserServiceImplTest.java: Rename the ambiguous user variable, and remove redundant assignments to sixFriendsWithOnlineStatusDtos and friendsWithOnlineStatusDtos.

### PR DESCRIPTION
**Pull request by K4sik**
# GreenCityUser PR
Fix Sonar Issues in GreenCityUser service and service-API modules

## Issue Link :clipboard:
#[7532](https://github.com/orgs/ita-social-projects/projects/43/views/1?pane=issue&itemId=81573167) 

## Changed
* ApiLocate.java by removing section @Parameters;
* CustomExceptionHandlerTest.java by removing unnecessary commented test cases and fixed assignment of values;
* ManagementSecurityControllerTest.java by removing useless assignments to local variable "dto";
* JwtTool.java - throw a dedicated exception IllegalArgumentException instead of using RuntimeException;
* Adde annotation @SuppressWarnings("java:S1118") to EmailAddressValidator, LanguageValidationUtils, and UrlValidator for skipping Sonar Issue;
* Removed usage of "initMocks" because of its deprecation and added @ExtendWith(MockitoExtension.class) instead in SearchCriteriaTest.java, CustomSpecificationTest.java, and UserSpecificationTest.java.
* Renamed field "notVerifiedUser" and refactored the code of the lambdas to have only one invocation possibly throwing an exception in OwnSecurityServiceImplTest.java;
* Removed block of commented-out lines of code which should be deleted VerifyEmailServiceImplTest.java;
* Renamed obj "user" which has already been declared, removed useless assignment to local variable "sixFriendsWithOnlineStatusDtos" and "friendsWithOnlineStatusDtos" in UserServiceImplTest.java.

# PR Checklist Forms

_(to be filled out by PR submitter)_
- [ ] Code is up-to-date with the dev branch.
- [X] You've successfully built and run the tests locally.
- [X] New or updated unit tests validate the change.
- [X] JIRA/ Github Issue number & title in PR title (ISSUE-#[7532](https://github.com/orgs/ita-social-projects/projects/43/views/1?pane=issue&itemId=81573167))
- [X] This template is filled (above this section).
- [X] Sonar's report does not contain bugs, vulnerabilities, security issues, code smells or duplication
- [X] NEED_REVIEW and READY_FOR_REVIEW labels are added.
- [X] All files reviewed before sending to reviewers

### CODE REVIEW

**Review by holotsvan — APPROVED** [review]

**Review by Maryna-511750 — APPROVED** [review]

File: service-api/src/main/java/greencity/security/jwt/JwtTool.java [hunk 1]
```diff
@@ -116,7 +116,7 @@ public String getEmailOutOfAccessToken(String token) {
         try {
             jsonNode = objectMapper.readTree(payload);
         } catch (Exception e) {
-            throw new RuntimeException("Error parsing JSON payload", e);
+            throw new IllegalArgumentException("Error parsing JSON payload", e);
```
Comment (KizerovDmitriy) [inline service-api/src/main/java/greencity/security/jwt/JwtTool.java:119]: did we having handler for current exception?

**Review by KizerovDmitriy — CHANGES_REQUESTED** [review]

File: service-api/src/main/java/greencity/security/jwt/JwtTool.java (hunk 1 above)
Comment (K4sik) [reply service-api/src/main/java/greencity/security/jwt/JwtTool.java:119]: Yes, now we have exception handler for IllegalArgumentException.

**Review by KizerovDmitriy — APPROVED** [review]
